name: build

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  schedule:
  - cron: "0 0 1 * *"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: ljmf00/archlinux:devel
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Checkout data 🔽
      uses: actions/checkout@v3
      with:
        repository: alexjorgef/cv-data
        token: ${{ secrets.DATA_GITHUB_TOKEN }}
        path: cv-data
    - name: Inject data 🔨
      run: cp -rp cv-data/production/* .
    - name: Install dependencies
      run: |
        pacman -Syy --needed --noconfirm --noprogressbar texlive-most
    - name: Build Curriculum Vitae 🔨
      run: SOURCE_DATE_EPOCH=1 xelatex cv.tex
    - name: Build Résumé 🔨
      run: SOURCE_DATE_EPOCH=1 xelatex resume.tex
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: github.ref == 'refs/heads/main'
      with:
        name: cv-artifacts
        path: |
          cv.pdf
          resume.pdf
        if-no-files-found: error
  deploy:
    needs: build
    if: success() && github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.ghpages-deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: cv-artifacts
        path: cv-output
    - name: Copy landing page files
      run: cp index.html logo.png favicon.ico cv-output/
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: cv-output
    - name: Deploy to GitHub Pages
      id: ghpages-deployment
      uses: actions/deploy-pages@v2
    - name: Upload and pin to Web3 Storage 🚀
      uses: web3-storage/add-to-web3@59774ff5ca3e7fd57fbd25ad62557a408a6122fc
      id: web3storage
      with:
        web3_token: ${{ secrets.WEB3STORAGE_TOKEN }}
        path_to_add: cv-output
        wrap_with_directory: false
    - name: Deploy _dnslink to Cloudflare 🚀
      run: |
        curl -X PUT "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE }}/dns_records/${{ secrets.CLOUDFLARE_RECORD }}" \
          -H "X-Auth-Email: ${{ secrets.CLOUDFLARE_XAUTH_EMAIL }}" \
          -H "X-Auth-Key: ${{ secrets.CLOUDFLARE_XAUTH_KEY }}" \
          -H "Content-Type: application/json" \
          --data '{"type":"TXT","name":"_dnslink.${{ vars.DNS_CNAME }}","content":"dnslink=/ipfs/${{ steps.web3storage.outputs.cid }}","ttl":1}' > /dev/null 2>&1
